services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=living-life
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_ROOT_PASSWORD=pwd
    ports:
      - "5432:5432"

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
      - "8000:8000"  # Expose port for debugging
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/living-life
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=pwd
    depends_on:
      - postgres
    volumes:
      - .:/app  # Bind your local directory to the container for live reload
    command: ./mvnw spring-boot:run  # Run the application in dev mode
